### ISSUE TITLE
Output should be entirely generated from generate.py

### ISSUE THREAD

**Issue by Endi1** [fosjump/fosjump#6]
It would be better if `generate.py` all the input folder the first time it's run, instead of simply modifying files in the already existing directory. I can implement this if everyone agrees.

**Comment by SamyMe** [comment]
I see. How do you think about doing that?

**Comment by Endi1** [comment]
In broad lines:
- `generate.py` creates the output folder 
- parses the data from `projects.yml` 
- with that data plus the templates creates the needed `.html` files
- put everything in the freshly generated `output` folder

This way we can keep the size of the project that needs downloading small and lightweight, especially if lots of projects start getting added.

**Comment by SamyMe** [comment]
What about the CSS/JS files? where is it supposed to get them from? Personally, I thought about linking the output to [fosjump.github.io](http://github.com/fosjump/fosjump.github.io) repo, something like that.

**Comment by Endi1** [comment]
There's no way to generate static assets, so they should be included in the repo in a folder. I'm thinking of only generating the html files, kinda like Jekyll or Pelican if you have any experience with any of them.

**Comment by SamyMe** [comment]
It's actually the case. If you remove the html files they get regenerated using the templates.

Btw, what is the name of the python package needed for the server?

**Comment by Endi1** [comment]
> Btw, what is the name of the python package needed for the server?

It uses the built-in SimpleHTTPServer, it may be Python3 only though...

> It's actually the case. If you remove the html files they get regenerated using the templates.

Alright then, I'll close this issue.
